import type { IGetUserResponse, IPostRefreshTokenResponse, IPostSignInRequest, IPostSignInResponse, IPostSignupRequest, IPostSignupResponse, TDeleteAccountResponse, IPostChangePasswordResponse, TPostLogoutResponse, IUpdateUserRequest, IPostForgotPasswordRequest, IPostForgotPasswordResponse, IGetGoogleLoginRequest, IResetPasswordRequest, ISendEmailRequest, CreateOrganizationPayload, AddMemberPayload, UpdateMemberPayload, CreateInvitePayload, CreateOrbitPayload, AddMemberToOrbitPayload, UpdateOrbitPayload, IGetMicrosoftLoginRequest } from './api.interfaces';
import type { OrbitRoleEnum } from '@/components/orbits/orbits.interfaces';
import { BucketSecretsApi } from './bucket-secrets';
import { OrbitCollectionsApi } from './orbit-collections';
import { ArtifactsApi } from './artifacts';
import { ApiKeysApi } from './api-keys';
import { SatellitesApi } from './satellites';
import { OrbitSecretsApi } from './orbit-secrets';
import { DeploymentsApi } from './deployments';
import { PrismaApi } from './prisma';
import { OrbitTracksApi } from './orbit-tracks';
export declare class ApiClass {
    private api;
    bucketSecrets: BucketSecretsApi;
    orbitCollections: OrbitCollectionsApi;
    artifacts: ArtifactsApi;
    apiKeys: ApiKeysApi;
    satellites: SatellitesApi;
    orbitSecrets: OrbitSecretsApi;
    deployments: DeploymentsApi;
    dataAgent: PrismaApi;
    orbitTracks: OrbitTracksApi;
    constructor();
    signUp(data: IPostSignupRequest): Promise<IPostSignupResponse>;
    signIn(data: IPostSignInRequest): Promise<IPostSignInResponse>;
    googleLogin(params: IGetGoogleLoginRequest): Promise<IPostSignInResponse>;
    microsoftLogin(params: IGetMicrosoftLoginRequest): Promise<IPostSignInResponse>;
    refreshToken(): Promise<IPostRefreshTokenResponse>;
    forgotPassword(data: IPostForgotPasswordRequest): Promise<IPostForgotPasswordResponse>;
    getMe(): Promise<IGetUserResponse>;
    updateUser(data: IUpdateUserRequest): Promise<IPostChangePasswordResponse>;
    deleteUser(): Promise<TDeleteAccountResponse>;
    logout(): Promise<TPostLogoutResponse>;
    resetPassword(data: IResetPasswordRequest): Promise<void>;
    sendEmail(data: ISendEmailRequest): Promise<void>;
    getInvitations(): Promise<any>;
    createInvite(organizationId: string, data: CreateInvitePayload): Promise<any>;
    acceptInvitation(inviteId: string): Promise<void>;
    rejectInvitation(inviteId: string): Promise<void>;
    cancelInvitation(organizationId: string, inviteId: string): Promise<void>;
    getOrganizations(): Promise<any>;
    createOrganization(data: CreateOrganizationPayload): Promise<any>;
    updateOrganization(organizationId: string, data: CreateOrganizationPayload): Promise<any>;
    deleteOrganization(organizationId: string): Promise<void>;
    leaveOrganization(organizationId: string): Promise<void>;
    getOrganization(id: string): Promise<any>;
    getOrganizationMembers(organizationId: string): Promise<any>;
    addMemberToOrganization(organizationId: string, data: AddMemberPayload): Promise<any>;
    updateOrganizationMember(organizationId: string, memberId: string, data: UpdateMemberPayload): Promise<any>;
    deleteMemberFormOrganization(organizationId: string, memberId: string): Promise<any>;
    getOrganizationOrbits(organizationId: string): Promise<any>;
    createOrbit(organization_id: string, data: CreateOrbitPayload): Promise<any>;
    getOrbitDetails(organizationId: string, orbitId: string): Promise<any>;
    updateOrbit(organizationId: string, data: UpdateOrbitPayload): Promise<any>;
    deleteOrbit(organizationId: string, orbitId: string): Promise<any>;
    getOrbitMembers(organizationId: string, orbitId: string): Promise<any>;
    addMemberToOrbit(organizationId: string, data: AddMemberToOrbitPayload): Promise<any>;
    updateOrbitMember(organizationId: string, orbitId: string, data: {
        id: string;
        role: OrbitRoleEnum;
    }): Promise<any>;
    deleteOrbitMember(organizationId: string, orbitId: string, memberId: string): Promise<any>;
}
