import { type FlowExportObject } from '@vue-flow/core';
import { type PromptNode } from '@/components/express-tasks/prompt-fusion/interfaces';
import type { PayloadData, PromptFusionPayload, ProviderModelsEnum, ProvidersEnum, ProviderSetting, ProviderWithModels } from './prompt-fusion.interfaces';
import { Observable } from '@/utils/observable/Observable';
import { EvaluationModesEnum } from './prompt-fusion.interfaces';
type Events = {
    CHANGE_SETTINGS_STATUS: boolean;
    CHANGE_OPTIMIZATION_STATE: boolean;
    OPEN_PROVIDER_SETTINGS: ProvidersEnum;
    CLOSE_PROVIDER_SETTINGS: void;
    CHANGE_TEACHER_MODEL: ProviderModelsEnum | null;
    CHANGE_STUDENT_MODEL: ProviderModelsEnum | null;
    CHANGE_TRAINING_STATE: boolean;
    CHANGE_PREDICT_VISIBLE: boolean;
    CHANGE_MODEL_ID: string;
    CHANGE_PREDICTION_FIELDS: string[] | null;
    CHANGE_AVAILABLE_MODELS: ProviderWithModels[];
};
declare class PromptFusionServiceClass extends Observable<Events> {
    providers: import("./prompt-fusion.interfaces").BaseProviderInfo[];
    availableModels: ProviderWithModels[];
    isSettingsOpened: boolean;
    openedProviderSettings: ProvidersEnum | null;
    isOptimizationOpened: boolean;
    teacherModel: ProviderModelsEnum | null;
    studentModel: ProviderModelsEnum | null;
    evaluationMode: EvaluationModesEnum;
    evaluationCriteriaList: string[];
    nodesData: PayloadData | null;
    payload: PromptFusionPayload | null;
    isTrainingActive: boolean;
    isPredictVisible: boolean;
    modelId: string | null;
    taskDescription: string;
    trainingData: Record<string, []> | null;
    predictionFields: string[] | null;
    modelBlob: Blob | null;
    inputs: string[];
    outputs: string[];
    constructor();
    openSettings(): void;
    closeSettings(): void;
    openProviderSettings(provider: ProvidersEnum): void;
    updateProviderSettings(provider: ProvidersEnum, settings: ProviderSetting[]): void;
    closeProviderSettings(): void;
    changeOptimizationState(isOpen: boolean): void;
    changeAvailableModels(): void;
    updateTeacherModel(model: ProviderModelsEnum | null): void;
    updateStudentModel(model: ProviderModelsEnum | null): void;
    checkIsOptimizationAvailable(): void;
    getProviderSettings(providerId: ProvidersEnum): ProviderSetting[];
    runOptimization(): Promise<void>;
    prepareData(object: FlowExportObject): void;
    endTraining(): void;
    togglePredict(): void;
    saveTrainingData(data: Record<string, []>, inputFields: string[], outputFields: string[]): void;
    resetState(): void;
    getConnectedProviders(): import("./prompt-fusion.interfaces").BaseProviderInfo[];
    downloadModel(): void;
    createFlowFromMetadata(metadata: PayloadData): {
        nodes: PromptNode[];
        edges: Edge[];
    };
    private haveDuplicatedFields;
    private prepareNodesData;
    private getEdgesFromObject;
    private getFieldsDataFromNodeData;
    private getTeacherProviderData;
    private getStudentProviderData;
    private setModelId;
    private savePredictionFields;
    private saveModel;
    private getNodeIconByNodeType;
    private getNodeIconColorByNodeType;
    private getFieldHandlePosition;
}
export declare const promptFusionService: PromptFusionServiceClass;
export {};
