from luml_satellite._version import KIT_NAME, KIT_VERSION, SATELLITE_API_VERSION
from luml_satellite.tokens import TokenDeriver, TokenPurpose, mint_artifact_token
from luml_satellite.wire import (
    ArtifactDownload,
    AuthenticationFailure,
    ContractComparison,
    ContractOperation,
    ContractVerdict,
    Deployment,
    DeploymentInfo,
    DeploymentStatus,
    DeploymentUpdate,
    ErrorMessage,
    Healthz,
    InferenceAccessIn,
    InferenceAccessOut,
    KitInfo,
    LegacyAddressRequired,
    MonitoringIntrospection,
    MonitoringSessionInfo,
    MonitoringTokenClaims,
    PairedSatellite,
    PairingRequest,
    PlatformAuthenticationError,
    PlatformClient,
    PlatformError,
    PlatformRefusal,
    PlatformRefusalError,
    SatelliteContract,
    SatelliteQueueTask,
    SatelliteTaskStatus,
    SatelliteTaskType,
    Secret,
    compare_contract,
)

__version__ = KIT_VERSION

__all__ = [
    "KIT_NAME",
    "KIT_VERSION",
    "SATELLITE_API_VERSION",
    "ArtifactDownload",
    "AuthenticationFailure",
    "ContractComparison",
    "ContractOperation",
    "ContractVerdict",
    "Deployment",
    "DeploymentInfo",
    "DeploymentStatus",
    "DeploymentUpdate",
    "ErrorMessage",
    "Healthz",
    "InferenceAccessIn",
    "InferenceAccessOut",
    "KitInfo",
    "LegacyAddressRequired",
    "MonitoringIntrospection",
    "MonitoringSessionInfo",
    "MonitoringTokenClaims",
    "PairedSatellite",
    "PairingRequest",
    "PlatformAuthenticationError",
    "PlatformClient",
    "PlatformError",
    "PlatformRefusal",
    "PlatformRefusalError",
    "SatelliteContract",
    "SatelliteQueueTask",
    "SatelliteTaskStatus",
    "SatelliteTaskType",
    "Secret",
    "TokenDeriver",
    "TokenPurpose",
    "compare_contract",
    "mint_artifact_token",
]
