"""The platform dev stack (Docker Compose) and its REST API."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import httpx

from luml_demo.config import DemoConfig
from luml_demo.shell import compose, port_is_free, say, wait_for

API_PREFIX = "/v1"


def compose_files(config: DemoConfig) -> list[Path]:
    return [config.repo_root / "dev" / "docker-compose.yml", override_path(config)]


def override_path(config: DemoConfig) -> Path:
    return config.home / "platform" / "docker-compose.override.yml"


def render_override(config: DemoConfig) -> str:
    """Compose override that moves every published port and the URLs that embed them."""
    web = config.web_url
    return f"""# Generated by luml-demo; edit the LUML_DEMO_* environment instead.
services:
  postgres:
    ports: !override
      - "{config.pg_port}:5432"
  minio:
    ports: !override
      - "{config.minio_port}:9000"
      - "{config.minio_console_port}:9001"
  backend:
    ports: !override
      - "{config.api_port}:8000"
    environment:
      CORS_ORIGINS: "{web},http://127.0.0.1:{config.web_port}"
      CONFIRM_EMAIL_REDIRECT_URL: "{web}/email-confirmed"
      CONFIRM_EMAIL_URL: "{config.api_url}{API_PREFIX}/auth/confirm-email?confirmation_token="
      CHANGE_PASSWORD_URL: "{web}/change-password?token="
      APP_EMAIL_URL: "{web}/"
  seed:
    environment:
      DEV_BUCKET_ENDPOINT: "localhost:{config.minio_port}"
  frontend:
    ports: !override
      - "{config.web_port}:5173"
    environment:
      VITE_API_URL: "{config.api_url}"
      VITE_DOCS_URL: "{web}"
"""


def ensure_dev_env_file(config: DemoConfig) -> None:
    env_file = config.repo_root / "dev" / ".env"
    if env_file.exists():
        return
    env_file.write_text(f"UID={os.getuid()}\nGID={os.getgid()}\n")
    say(f"wrote {env_file}")


def check_ports(config: DemoConfig) -> None:
    taken = [
        port for port in (config.api_port, config.web_port, config.pg_port,
                          config.minio_port, config.minio_console_port)
        if not port_is_free(port)
    ]
    if taken:
        raise RuntimeError(
            f"ports already in use: {taken}. Stop the other service or set LUML_DEMO_*_PORT."
        )


def api_ready(config: DemoConfig) -> bool:
    return httpx.get(f"{config.api_url}/docs", timeout=3).status_code == 200


def web_ready(config: DemoConfig) -> bool:
    return httpx.get(f"{config.web_url}/", timeout=3).status_code == 200


def up(config: DemoConfig) -> None:
    ensure_dev_env_file(config)
    path = override_path(config)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_override(config))
    if not api_ready_quiet(config):
        check_ports(config)
    files = compose_files(config)
    compose(config.compose_project, files, "up", "-d", "--build", cwd=config.repo_root)
    wait_for("platform API", lambda: api_ready(config), timeout=600)
    compose(config.compose_project, files, "run", "--rm", "seed", cwd=config.repo_root)
    wait_for("web app (first run installs npm packages)", lambda: web_ready(config), timeout=1200)


def api_ready_quiet(config: DemoConfig) -> bool:
    try:
        return api_ready(config)
    except httpx.HTTPError:
        return False


def down(config: DemoConfig, *, volumes: bool) -> None:
    if not override_path(config).exists():
        say("platform override missing; nothing to stop")
        return
    args = ["down", "--remove-orphans"]
    if volumes:
        args.append("--volumes")
    compose(config.compose_project, compose_files(config), *args, cwd=config.repo_root, check=False)


def build_images(config: DemoConfig) -> None:
    compose(config.compose_project, compose_files(config), "build", cwd=config.repo_root)


class PlatformClient:
    """Thin REST client for the calls luml-api does not expose."""

    def __init__(self, base_url: str, token: str | None = None) -> None:
        self.base_url = base_url.rstrip("/")
        self._client = httpx.Client(base_url=self.base_url + API_PREFIX, timeout=60)
        self.token = token

    def _headers(self) -> dict[str, str]:
        return {"Authorization": f"Bearer {self.token}"} if self.token else {}

    def _request(self, method: str, path: str, **kwargs: Any) -> httpx.Response:
        response = self._client.request(method, path, headers=self._headers(), **kwargs)
        if response.status_code >= 400:
            raise RuntimeError(f"{method} {path} -> {response.status_code}: {response.text[:400]}")
        return response

    def signin(self, email: str, password: str) -> str:
        response = self._request("POST", "/auth/signin", json={"email": email, "password": password})
        jwt = response.cookies.get("access_token")
        if not jwt:
            raise RuntimeError("signin returned no access_token cookie")
        self.token = jwt
        self.user_id = str(response.json()["user_id"])
        return jwt

    def create_api_key(self) -> str:
        return str(self._request("POST", "/users/me/api-keys").json()["key"])

    def api_key_valid(self, key: str) -> bool:
        response = self._client.get("/auth/api-keys/validate", headers={"Authorization": f"Bearer {key}"})
        return response.status_code == 204

    def organizations(self) -> list[dict[str, Any]]:
        return list(self._request("GET", "/organizations").json())

    def orbits(self, org_id: str) -> list[dict[str, Any]]:
        return list(self._request("GET", f"/organizations/{org_id}/orbits").json())

    def create_orbit(self, org_id: str, name: str, bucket_secret_id: str, user_id: str) -> dict[str, Any]:
        payload = {
            "name": name,
            "bucket_secret_id": bucket_secret_id,
            "members": [{"user_id": user_id, "role": "admin"}],
        }
        return dict(self._request("POST", f"/organizations/{org_id}/orbits", json=payload).json())

    def satellites(self, org_id: str, orbit_id: str) -> list[dict[str, Any]]:
        return list(self._request("GET", f"/organizations/{org_id}/orbits/{orbit_id}/satellites").json())

    def create_satellite(self, org_id: str, orbit_id: str, name: str, description: str) -> dict[str, Any]:
        return dict(self._request(
            "POST", f"/organizations/{org_id}/orbits/{orbit_id}/satellites",
            json={"name": name, "description": description},
        ).json())

    def delete_satellite(self, org_id: str, orbit_id: str, satellite_id: str) -> None:
        self._request("DELETE", f"/organizations/{org_id}/orbits/{orbit_id}/satellites/{satellite_id}")

    def deployments(self, org_id: str, orbit_id: str) -> list[dict[str, Any]]:
        return list(self._request("GET", f"/organizations/{org_id}/orbits/{orbit_id}/deployments").json())

    def deployment(self, org_id: str, orbit_id: str, deployment_id: str) -> dict[str, Any]:
        return dict(self._request(
            "GET", f"/organizations/{org_id}/orbits/{orbit_id}/deployments/{deployment_id}",
        ).json())

    def create_deployment(self, org_id: str, orbit_id: str, payload: dict[str, Any]) -> dict[str, Any]:
        return dict(self._request(
            "POST", f"/organizations/{org_id}/orbits/{orbit_id}/deployments", json=payload,
        ).json())

    def delete_deployment(self, org_id: str, orbit_id: str, deployment_id: str) -> None:
        self._request("DELETE", f"/organizations/{org_id}/orbits/{orbit_id}/deployments/{deployment_id}")

    def monitoring_eligibility(self, org_id: str, orbit_id: str, deployment_id: str) -> dict[str, Any]:
        return dict(self._request(
            "GET",
            f"/organizations/{org_id}/orbits/{orbit_id}/deployments/{deployment_id}/monitoring/eligibility",
        ).json())

