"""Docker satellite stacks, one Compose project per satellite."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Any

from luml_demo.config import DemoConfig, SatelliteSpec
from luml_demo.platform import PlatformClient
from luml_demo.shell import compose, run, say, wait_for

AGENT_IMAGE = "luml-satellite-agent:latest"
MODEL_IMAGE = "luml-random-svc:latest"
MONITORING_INTERVAL_SEC = 15
# Enough five-minute windows to materialize a week of history in one worker tick.
MONITORING_BACKFILL_MAX_WINDOWS = 2016


def stack_dir(config: DemoConfig, spec: SatelliteSpec) -> Path:
    return config.sats_dir / spec.slug


def project_name(config: DemoConfig, spec: SatelliteSpec) -> str:
    return f"{config.compose_project}-sat-{spec.slug}"


def render_compose(config: DemoConfig, spec: SatelliteSpec) -> str:
    return f"""# Generated by luml-demo for satellite "{spec.name}".
name: {project_name(config, spec)}

networks:
  satellite-network:
    driver: bridge

volumes:
  greptimedb-data:

services:
  greptimedb:
    image: greptime/greptimedb:v0.13.1
    command: standalone start --http-addr=0.0.0.0:4000 --rpc-addr=0.0.0.0:4001
    networks:
      - satellite-network
    volumes:
      - greptimedb-data:/tmp/greptimedb
    ports:
      - "{spec.greptime_port}:4000"
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.127.0
    command: ["--config=/etc/otel/config.yaml"]
    networks:
      - satellite-network
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml:ro
    ports:
      - "{spec.otlp_port}:4317"
    depends_on:
      - greptimedb
    restart: unless-stopped

  agent:
    image: {AGENT_IMAGE}
    networks:
      satellite-network:
        aliases:
          - satellite-agent
    environment:
      SATELLITE_TOKEN: ${{SATELLITE_TOKEN:?Set SATELLITE_TOKEN in .env}}
      PLATFORM_URL: {config.platform_url_for_docker}
      BASE_URL: http://localhost:{spec.port}
      MODEL_IMAGE: {MODEL_IMAGE}
      POLL_INTERVAL_SEC: 2
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      MONITORING_ENABLED: "true"
      GREPTIMEDB_HOST: greptimedb
      MONITORING_FRAME_ANCESTORS: {config.web_url}
      MONITORING_INTERVAL_SEC: {MONITORING_INTERVAL_SEC}
      MONITORING_BACKFILL_MAX_WINDOWS: {MONITORING_BACKFILL_MAX_WINDOWS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: "0:0"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "{spec.port}:8000"
    depends_on:
      - otel-collector
    restart: unless-stopped
"""


def write_stack(config: DemoConfig, spec: SatelliteSpec, token: str) -> Path:
    directory = stack_dir(config, spec)
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "docker-compose.yml").write_text(render_compose(config, spec))
    shutil.copyfile(
        config.repo_root / "satellite" / "otel-collector-config.yaml",
        directory / "otel-collector-config.yaml",
    )
    (directory / ".env").write_text(f"SATELLITE_TOKEN={token}\n")
    return directory


def image_exists(name: str) -> bool:
    probe = subprocess.run(["docker", "image", "inspect", name], capture_output=True, check=False)
    return probe.returncode == 0


def ensure_images(config: DemoConfig, *, force: bool = False) -> None:
    satellite_dir = config.repo_root / "satellite"
    if force or not image_exists(AGENT_IMAGE):
        run(["docker", "build", "-t", AGENT_IMAGE, "-f",
             str(satellite_dir / "implementations" / "docker" / "Dockerfile"), str(satellite_dir)])
    if force or not image_exists(MODEL_IMAGE):
        run(["docker", "build", "-t", MODEL_IMAGE, str(config.repo_root / "model_servers" / "default")])


def up(config: DemoConfig, spec: SatelliteSpec) -> None:
    directory = stack_dir(config, spec)
    compose(project_name(config, spec), [directory / "docker-compose.yml"], "up", "-d", cwd=directory)


def down(config: DemoConfig, spec: SatelliteSpec, *, volumes: bool) -> None:
    directory = stack_dir(config, spec)
    if not (directory / "docker-compose.yml").exists():
        return
    args = ["down", "--remove-orphans"]
    if volumes:
        args.append("--volumes")
    compose(project_name(config, spec), [directory / "docker-compose.yml"], *args, cwd=directory,
            check=False)


def remove_model_containers(spec_slug: str) -> None:
    """Model containers outlive compose down; remove the ones this satellite launched."""
    listing = subprocess.run(
        ["docker", "ps", "-aq", "--filter", "name=^sat-"], capture_output=True, text=True, check=False,
    )
    ids = listing.stdout.split()
    if ids:
        say(f"removing {len(ids)} leftover model container(s) ({spec_slug})")
        subprocess.run(["docker", "rm", "-f", *ids], check=False, capture_output=True)


def satellite_record(client: PlatformClient, org_id: str, orbit_id: str, satellite_id: str) -> dict[str, Any]:
    for satellite in client.satellites(org_id, orbit_id):
        if str(satellite["id"]) == satellite_id:
            return satellite
    raise RuntimeError(f"satellite {satellite_id} disappeared from the platform")


def wait_paired(client: PlatformClient, org_id: str, orbit_id: str, satellite_id: str, name: str) -> None:
    def paired() -> bool:
        record = satellite_record(client, org_id, orbit_id, satellite_id)
        return bool(record.get("paired")) and record.get("status") == "active"

    wait_for(f"satellite {name} to pair", paired, timeout=300, interval=3)
