import { zodResolver } from '@primevue/forms/resolvers/zod';
import type { Orbit } from '@/lib/api/api.interfaces';
import type { CreateDeploymentForm } from '@/components/deployments/deployments.interfaces';
import type { Ref } from 'vue';
type Resolver = ReturnType<typeof zodResolver>;
export declare const signInResolver: Resolver;
export declare const signUpResolver: Resolver;
export declare const forgotPasswordResolver: Resolver;
export declare const resetPasswordResolver: Resolver;
export declare const userSettingResolver: Resolver;
export declare const userChangePasswordResolver: Resolver;
export declare const orbitCreatorResolver: (orbitsList: Orbit[]) => Resolver;
export declare const collectionCreatorResolver: Resolver;
export declare const collectionEditorResolver: Resolver;
export declare const artifactCreateResolver: Resolver;
export declare const artifactEditResolver: Resolver;
export declare const modelUploadResolver: Resolver;
export declare const satellitesResolver: Resolver;
export declare const createSecretResolver: Resolver;
export declare const updateSecretResolver: Resolver;
export declare const createDeploymentResolver: (formData: Ref<CreateDeploymentForm>) => Resolver;
export {};
