import type { Agent, AgentRepository, AgentTask, BrowseResult, MergePreview, Run, RunConfig, RunEdge, RunNode } from '@/lib/api/prisma/prisma.interfaces';
export declare const mockRepositories: AgentRepository[];
export declare const mockAgents: Agent[];
export declare const mockBranches: string[];
export declare const mockRunConfig: RunConfig;
export declare const mockTasks: AgentTask[];
export declare const mockRuns: Run[];
export declare const mockNodes: RunNode[];
export declare const mockEdges: RunEdge[];
export declare const mockMergePreview: MergePreview;
export declare const mockMergePreviewConflict: MergePreview;
export declare const mockBrowseResult: BrowseResult;
