import type {
  Agent,
  AgentRepository,
  AgentTask,
  BrowseResult,
  MergePreview,
  Run,
  RunConfig,
  RunEdge,
  RunNode,
} from '@/lib/api/prisma/prisma.interfaces'

const NOW = new Date('2026-04-20T14:00:00Z').toISOString()
const HOUR_AGO = new Date('2026-04-20T13:00:00Z').toISOString()
const YESTERDAY = new Date('2026-04-19T14:00:00Z').toISOString()

export const mockRepositories: AgentRepository[] = [
  { id: 'repo-1', name: 'ml-experiments', path: '/home/user/dev/ml-experiments' },
  { id: 'repo-2', name: 'nlp-benchmarks', path: '/home/user/dev/nlp-benchmarks' },
  {
    id: 'repo-3',
    name: 'deeply-nested-repo-with-a-long-path',
    path: '/home/user/dev/some/very/deeply/nested/path/deeply-nested-repo-with-a-long-path',
  },
]

export const mockAgents: Agent[] = [
  {
    id: 'claude',
    name: 'Claude Code',
    cli: 'claude',
    prompt_flag: '-p',
    auto_approve_flag: '--dangerously-skip-permissions',
    resume_flag: '--resume',
    default_args: [],
  },
  {
    id: 'codex',
    name: 'Codex',
    cli: 'codex',
    prompt_flag: '-p',
    auto_approve_flag: '--yes',
    resume_flag: '--resume',
    default_args: [],
  },
]

export const mockBranches = [
  'main',
  'develop',
  'feat/new-metric',
  'prisma/implement-a1b2c3',
  'prisma/fork-d4e5f6',
]

export const mockRunConfig: RunConfig = {
  max_depth: 2,
  max_children_per_fork: 2,
  max_debug_retries: 2,
  max_concurrency: 1,
  run_command_template: 'uv run main.py',
  agent_id: 'claude',
  auto_mode: false,
  auto_terminate_timeout: 30,
  implement_timeout: 3600,
  run_timeout: 0,
  debug_timeout: 1800,
  fork_timeout: 1200,
  max_log_tail: 10000,
  primary_metric: 'metric',
  luml_collection_id: null,
  luml_organization_id: null,
  luml_orbit_id: null,
}

export const mockTasks: AgentTask[] = [
  {
    id: 'task-pending',
    repository_id: 'repo-1',
    name: 'improve-accuracy',
    branch: 'prisma/improve-accuracy',
    worktree_path: '/tmp/wt/task-pending',
    agent_id: 'claude',
    status: 'pending',
    prompt: 'Improve the classifier accuracy by trying gradient boosting.',
    base_branch: 'main',
    created_at: HOUR_AGO,
    updated_at: HOUR_AGO,
  },
  {
    id: 'task-running',
    repository_id: 'repo-1',
    name: 'fix-flaky-test',
    branch: 'prisma/fix-flaky-test',
    worktree_path: '/tmp/wt/task-running',
    agent_id: 'claude',
    status: 'running',
    prompt: 'Investigate and fix the flaky test in tests/test_integration.py',
    base_branch: 'main',
    created_at: HOUR_AGO,
    updated_at: NOW,
    is_alive: true,
    session_id: 'sess-abc',
  },
  {
    id: 'task-waiting',
    repository_id: 'repo-2',
    name: 'add-dataset-loader',
    branch: 'prisma/add-dataset-loader',
    worktree_path: '/tmp/wt/task-waiting',
    agent_id: 'claude',
    status: 'waiting_input',
    prompt: 'Add HF dataset loader support.',
    base_branch: 'develop',
    created_at: YESTERDAY,
    updated_at: NOW,
    has_waiting_input: true,
    session_id: 'sess-def',
  },
  {
    id: 'task-succeeded',
    repository_id: 'repo-1',
    name: 'refactor-utils',
    branch: 'prisma/refactor-utils',
    worktree_path: '/tmp/wt/task-succeeded',
    agent_id: 'claude',
    status: 'succeeded',
    prompt: 'Refactor the shared utils module.',
    base_branch: 'main',
    created_at: YESTERDAY,
    updated_at: HOUR_AGO,
  },
  {
    id: 'task-failed',
    repository_id: 'repo-2',
    name: 'broken-migration',
    branch: 'prisma/broken-migration',
    worktree_path: '/tmp/wt/task-failed',
    agent_id: 'claude',
    status: 'failed',
    prompt: 'Migrate to new schema.',
    base_branch: 'main',
    created_at: YESTERDAY,
    updated_at: YESTERDAY,
  },
  {
    id: 'task-merged',
    repository_id: 'repo-1',
    name: 'docs-update',
    branch: 'prisma/docs-update',
    worktree_path: '/tmp/wt/task-merged',
    agent_id: 'claude',
    status: 'merged',
    prompt: 'Update docs.',
    base_branch: 'main',
    created_at: YESTERDAY,
    updated_at: HOUR_AGO,
  },
]

export const mockRuns: Run[] = [
  {
    id: 'run-running',
    repository_id: 'repo-1',
    name: 'hyperparam-search',
    objective: 'Beat baseline accuracy on CIFAR-10 within 30 epochs.',
    status: 'running',
    config: mockRunConfig,
    base_branch: 'main',
    best_node_id: 'node-run-2',
    discovered_metric_keys: ['metric', 'accuracy'],
    created_at: HOUR_AGO,
    updated_at: NOW,
  },
  {
    id: 'run-succeeded',
    repository_id: 'repo-1',
    name: 'baseline',
    objective: 'Establish a baseline.',
    status: 'succeeded',
    config: mockRunConfig,
    base_branch: 'main',
    best_node_id: 'node-run-1',
    discovered_metric_keys: ['metric'],
    created_at: YESTERDAY,
    updated_at: HOUR_AGO,
  },
]

export const mockNodes: RunNode[] = [
  {
    id: 'node-impl-1',
    run_id: 'run-running',
    parent_node_id: null,
    node_type: 'implement',
    status: 'succeeded',
    depth: 0,
    payload: {},
    result: {},
    worktree_path: '/tmp/wt/node-impl-1',
    branch: 'prisma/impl-1',
    debug_retries: 0,
    created_at: HOUR_AGO,
    updated_at: HOUR_AGO,
  },
  {
    id: 'node-run-1',
    run_id: 'run-running',
    parent_node_id: 'node-impl-1',
    node_type: 'run',
    status: 'succeeded',
    depth: 1,
    payload: {},
    result: { artifacts: { metric: 0.874 } },
    worktree_path: '/tmp/wt/node-run-1',
    branch: 'prisma/run-1',
    debug_retries: 0,
    created_at: HOUR_AGO,
    updated_at: NOW,
  },
  {
    id: 'node-run-2',
    run_id: 'run-running',
    parent_node_id: 'node-impl-1',
    node_type: 'run',
    status: 'succeeded',
    depth: 1,
    payload: {},
    result: { artifacts: { metric: 0.921 } },
    worktree_path: '/tmp/wt/node-run-2',
    branch: 'prisma/run-2',
    debug_retries: 0,
    created_at: HOUR_AGO,
    updated_at: NOW,
  },
  {
    id: 'node-run-running',
    run_id: 'run-running',
    parent_node_id: 'node-impl-1',
    node_type: 'run',
    status: 'running',
    depth: 1,
    payload: {},
    result: {},
    worktree_path: '/tmp/wt/node-run-running',
    branch: 'prisma/run-running',
    debug_retries: 0,
    created_at: HOUR_AGO,
    updated_at: NOW,
    is_alive: true,
    session_id: 'sess-running',
  },
  {
    id: 'node-waiting',
    run_id: 'run-running',
    parent_node_id: null,
    node_type: 'implement',
    status: 'waiting_input',
    depth: 0,
    payload: {},
    result: {},
    worktree_path: '/tmp/wt/node-waiting',
    branch: 'prisma/waiting',
    debug_retries: 0,
    created_at: HOUR_AGO,
    updated_at: NOW,
    session_id: 'sess-waiting',
  },
  {
    id: 'node-failed',
    run_id: 'run-running',
    parent_node_id: 'node-impl-1',
    node_type: 'run',
    status: 'failed',
    depth: 1,
    payload: {},
    result: {},
    worktree_path: '/tmp/wt/node-failed',
    branch: 'prisma/failed',
    debug_retries: 2,
    created_at: HOUR_AGO,
    updated_at: NOW,
  },
]

export const mockEdges: RunEdge[] = [
  {
    id: 'edge-1',
    run_id: 'run-running',
    from_node_id: 'node-impl-1',
    to_node_id: 'node-run-1',
    reason: 'auto',
  },
  {
    id: 'edge-2',
    run_id: 'run-running',
    from_node_id: 'node-impl-1',
    to_node_id: 'node-run-2',
    reason: 'fork',
  },
]

export const mockMergePreview: MergePreview = {
  branch: 'prisma/refactor-utils',
  base_branch: 'main',
  stats: {
    commits_ahead: 4,
    files_changed: 7,
    insertions: 184,
    deletions: 62,
  },
  commit_messages: [
    'Extract shared helpers',
    'Remove dead code paths',
    'Update tests to cover new helpers',
    'chore: tidy imports',
  ],
  changed_files: [
    'src/utils/shared.py',
    'src/utils/__init__.py',
    'src/core/pipeline.py',
    'src/core/loaders.py',
    'tests/test_shared.py',
    'tests/test_pipeline.py',
    'README.md',
  ],
  can_fast_forward: true,
}

export const mockMergePreviewConflict: MergePreview = {
  ...mockMergePreview,
  can_fast_forward: false,
}

export const mockBrowseResult: BrowseResult = {
  current: '/home/user/dev',
  parent: '/home/user',
  is_git: false,
  dirs: [
    { name: 'ml-experiments', path: '/home/user/dev/ml-experiments', is_git: true },
    { name: 'nlp-benchmarks', path: '/home/user/dev/nlp-benchmarks', is_git: true },
    { name: 'scratch', path: '/home/user/dev/scratch', is_git: false },
    { name: 'docs', path: '/home/user/dev/docs', is_git: false },
  ],
}
