import type { Meta, StoryObj } from '@storybook/vue3';
import GraphNodeCard from '@/components/prisma/GraphNodeCard.vue';
import './_mockApi';
declare const meta: Meta<typeof GraphNodeCard>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const ImplementSucceeded: Story;
export declare const RunSucceeded: Story;
export declare const RunBest: Story;
export declare const Running: Story;
export declare const WaitingInput: Story;
export declare const Failed: Story;
