"""Added satellites and models limits

Revision ID: 024
Revises: 023
Create Date: 2025-11-10 15:35:27.515029

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "024"
down_revision: str | None = "023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_collections_orbit_id"), "collections", ["orbit_id"], unique=False
    )
    op.create_index(
        op.f("ix_model_artifacts_collection_id"),
        "model_artifacts",
        ["collection_id"],
        unique=False,
    )
    op.add_column(
        "organizations",
        sa.Column("satellites_limit", sa.Integer(), server_default="2", nullable=False),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "model_artifacts_limit", sa.Integer(), server_default="200", nullable=False
        ),
    )
    op.create_index(
        op.f("ix_satellites_orbit_id"), "satellites", ["orbit_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_satellites_orbit_id"), table_name="satellites")
    op.drop_column("organizations", "model_artifacts_limit")
    op.drop_column("organizations", "satellites_limit")
    op.drop_index(
        op.f("ix_model_artifacts_collection_id"), table_name="model_artifacts"
    )
    op.drop_index(op.f("ix_collections_orbit_id"), table_name="collections")
    # ### end Alembic commands ###
