"""Added type to bucket secrets

Revision ID: 027
Revises: 026
Create Date: 2025-12-04 12:40:10.997173

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "027"
down_revision: str | None = "026"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bucket_secrets", sa.Column("type", sa.String(), nullable=True))
    op.execute("UPDATE bucket_secrets SET type = 's3' WHERE type IS NULL")
    op.alter_column("bucket_secrets", "type", nullable=False)
    op.execute(
        "UPDATE bucket_secrets SET region = 'PLEASE_ADD_REGION_HERE' "
        "WHERE region IS NULL AND type = 's3'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bucket_secrets", "type")
    # ### end Alembic commands ###
