{{- if not .Values.satellite.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "luml.tokenSecretName" . | quote }}
  labels:
    {{- include "luml.labels" (dict "root" . "component" "satellite") | nindent 4 }}
type: Opaque
stringData:
  satellite-token: {{ .Values.satellite.token | quote }}
{{- end }}
