{{- $usernameSet := not (empty .Values.monitoring.store.username) -}}
{{- $passwordSet := not (empty .Values.monitoring.store.password) -}}
{{- if ne $usernameSet $passwordSet -}}
{{- fail "monitoring.store.username and monitoring.store.password must be set together" -}}
{{- end -}}
{{- if and .Values.monitoring.enabled (not .Values.monitoring.store.existingSecret) $usernameSet }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "luml.storeSecretName" . | quote }}
  labels:
    {{- include "luml.labels" (dict "root" . "component" "store") | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.monitoring.store.username | quote }}
  password: {{ .Values.monitoring.store.password | quote }}
{{- end }}
