{{- if and .Values.monitoring.enabled .Values.monitoring.sessionSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "luml.monitoringSecretName" . | quote }}
  labels:
    {{- include "luml.labels" (dict "root" . "component" "dashboard") | nindent 4 }}
type: Opaque
stringData:
  session-secret: {{ .Values.monitoring.sessionSecret | quote }}
{{- end }}
