apiVersion: v1
kind: Secret
metadata:
  name: {{ include "luml.derivationSecretName" . | quote }}
  labels:
    {{- include "luml.labels" (dict "root" . "component" "satellite") | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  derivation-key: {{ include "luml.derivationKey" . | quote }}
