"""Deployments, Satellites, Orbit Secrets updates

Revision ID: 012
Revises: 011
Create Date: 2025-08-27 12:44:34.378312

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "012"
down_revision: str | None = "011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deployments", sa.Column("model_id", sa.Integer(), nullable=False))
    op.add_column(
        "deployments",
        sa.Column(
            "secrets",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "deployments", sa.Column("created_by_user", sa.String(), nullable=True)
    )
    op.add_column(
        "deployments",
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.drop_constraint(
        "deployments_created_by_user_id_fkey", "deployments", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "deployments",
        "model_artifacts",
        ["model_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("deployments", "secret_ids")
    op.drop_column("deployments", "model_uri")
    op.drop_column("deployments", "created_by_user_id")
    op.add_column("satellites", sa.Column("base_url", sa.String(), nullable=True))
    op.alter_column(
        "satellites",
        "capabilities",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::character varying[]"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "satellites",
        "capabilities",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::character varying[]"),
    )
    op.drop_column("satellites", "base_url")
    op.add_column(
        "deployments",
        sa.Column(
            "created_by_user_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "deployments",
        sa.Column("model_uri", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "deployments",
        sa.Column(
            "secret_ids",
            postgresql.ARRAY(sa.INTEGER()),
            server_default=sa.text("'{}'::integer[]"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "deployments", type_="foreignkey")
    op.create_foreign_key(
        "deployments_created_by_user_id_fkey",
        "deployments",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("deployments", "tags")
    op.drop_column("deployments", "created_by_user")
    op.drop_column("deployments", "secrets")
    op.drop_column("deployments", "model_id")
    # ### end Alembic commands ###
