"""Satellite deployments deletion

Revision ID: 022
Revises: 021
Create Date: 2025-11-04 15:13:53.998919

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "022"
down_revision: str | None = "021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "deployments_satellite_id_fkey", "deployments", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "deployments", "satellites", ["satellite_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "deployments", type_="foreignkey")
    op.create_foreign_key(
        "deployments_satellite_id_fkey",
        "deployments",
        "satellites",
        ["satellite_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
