"""Indexes for model metrcis and tags

Revision ID: 029
Revises: 028
Create Date: 2026-01-06 19:56:27.478059

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "029"
down_revision: str | None = "028"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_model_artifacts_metrics_gin",
        "model_artifacts",
        ["metrics"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_model_artifacts_tags_gin",
        "model_artifacts",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_model_artifacts_tags_gin",
        table_name="model_artifacts",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_model_artifacts_metrics_gin",
        table_name="model_artifacts",
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
