"""Renamed artifacts index

Revision ID: 031
Revises: 030
Create Date: 2026-02-02 16:41:28.410723

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "031"
down_revision: str | None = "030"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_model_artifacts_collection_id"), table_name="artifacts")
    op.create_index(
        op.f("ix_artifacts_collection_id"), "artifacts", ["collection_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artifacts_collection_id"), table_name="artifacts")
    op.create_index(
        op.f("ix_model_artifacts_collection_id"),
        "artifacts",
        ["collection_id"],
        unique=False,
    )
    # ### end Alembic commands ###
