"""removed unique track nameconstraint

Revision ID: 034
Revises: 033
Create Date: 2026-06-11 14:13:15.068402

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "034"
down_revision: str | None = "033"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_tracks_orbit_id_name"), "tracks", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_tracks_orbit_id_name"),
        "tracks",
        ["orbit_id", "name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
