#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "pydoc-markdown>=4.8.0,<5.0.0",
# ]
# ///
"""
Regenerate the reference docs for both Python SDKs.

Run with: uv run generate_docs.py

The rendering pipeline lives in sdk_docs_generate.py; this file only says what
to render: for each SDK, the input package root, the output docs folder, and
the module -> page mapping. Page paths mirror the autogenerated Docusaurus
sidebars, so a module's page path is its place in the sidebar. Docusaurus
ignores files starting with "_", which is why private modules such as
`_client` map to explicit page names.

Example scripts are rendered too: one page per script, its module docstring
followed by its code, in the order of the examples README, and the README
itself as the index page of the examples category.
"""

import ast
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPT_DIR))

from sdk_docs_generate import (  # noqa: E402
    escape_mdx_syntax,
    render_module_markdown,
)

PROJECT_ROOT = SCRIPT_DIR.parent


@dataclass(frozen=True)
class DocsTarget:
    """One SDK to document: where to import from and where the pages go."""

    label: str
    import_root: Path
    output_dir: Path
    # module path -> page path without extension, relative to output_dir
    modules: dict[str, str]


TARGETS = [
    DocsTarget(
        label="API SDK (luml_api)",
        import_root=PROJECT_ROOT / "sdk" / "python" / "api",
        output_dir=SCRIPT_DIR / "docs" / "api-reference",
        modules={
            "luml_api._client": "client/client",
            "luml_api._exceptions": "client/exceptions",
            "luml_api._types": "resources/types",
            "luml_api.utils.progress": "resources/progress_handler",
            "luml_api.resources.artifacts": "resources/artifacts",
            "luml_api.resources.bucket_secrets": "resources/bucket-secrets",
            "luml_api.resources.collections": "resources/collections",
            "luml_api.resources.deployments": "resources/deployments",
            "luml_api.resources.monitoring": "resources/monitoring",
            "luml_api.resources.orbits": "resources/orbits",
            "luml_api.resources.organizations": "resources/organizations",
            "luml_api.resources.satellites": "resources/satellites",
            "luml_api.resources.tracks": "resources/tracks",
        },
    ),
    DocsTarget(
        label="SDK (luml)",
        import_root=PROJECT_ROOT / "sdk" / "python" / "sdk",
        output_dir=SCRIPT_DIR / "docs" / "sdk",
        modules={
            "luml.artifacts.model": "artifacts/model",
            "luml.llm._client": "llm/client",
            "luml.llm._exceptions": "llm/exceptions",
            "luml.experiments.tracker": "experiments/tracker",
            "luml.experiments.backends.sqlite": "experiments/backends/sqlite",
            "luml.experiments.evaluation.evaluate": "experiments/evaluation/evaluate",
            "luml.experiments.evaluation.types": "experiments/evaluation/types",
            "luml.experiments.evaluation.scorers.builtin.completeness": (
                "experiments/evaluation/completeness"
            ),
            "luml.experiments.evaluation.scorers.builtin.correctness": (
                "experiments/evaluation/correctness"
            ),
            "luml.experiments.evaluation.scorers.builtin.prompt_alignment": (
                "experiments/evaluation/prompt_alignment"
            ),
            "luml.experiments.evaluation.scorers.builtin.relevancy": (
                "experiments/evaluation/relevancy"
            ),
            "luml.experiments.evaluation.scorers.builtin.summarization": (
                "experiments/evaluation/summarization"
            ),
            "luml.integrations.catboost.packaging": "integrations/catboost",
            "luml.integrations.langgraph.packaging": "integrations/langgraph",
            "luml.integrations.lightgbm.packaging": "integrations/lightgbm",
            "luml.integrations.sklearn.packaging": "integrations/sklearn",
            "luml.integrations.xgboost.packaging": "integrations/xgboost",
        },
    ),
]


@dataclass(frozen=True)
class ExamplesTarget:
    """A folder of example scripts: one page per script, in README order."""

    label: str
    source_dir: Path
    output_dir: Path


EXAMPLES = [
    ExamplesTarget(
        label="API SDK examples (luml_api)",
        source_dir=PROJECT_ROOT / "sdk" / "python" / "api" / "examples",
        output_dir=SCRIPT_DIR / "docs" / "api-reference" / "examples",
    ),
]


def read_examples_index(readme: Path) -> tuple[list[str], dict[str, str]]:
    """Script order and one-line descriptions, from the README's table."""
    order: list[str] = []
    descriptions: dict[str, str] = {}
    if not readme.exists():
        return order, descriptions
    for line in readme.read_text().splitlines():
        match = re.match(r"\|\s*`(\w+)\.py`\s*\|\s*(.*?)\s*\|\s*$", line)
        if match:
            order.append(match.group(1))
            descriptions[match.group(1)] = match.group(2)
    return order, descriptions


def render_example_markdown(script: Path, position: int, description: str) -> str:
    """One example page: front matter, the module docstring, then the code."""
    source = script.read_text()
    module = ast.parse(source)
    docstring = ast.get_docstring(module) or ""
    code_lines = source.splitlines()
    first = module.body[0] if module.body else None
    if docstring and isinstance(first, ast.Expr) and first.end_lineno:
        code_lines = code_lines[first.end_lineno :]
    code = "\n".join(code_lines).strip("\n")

    front_matter = [f"title: {script.name}", f"sidebar_position: {position}"]
    if description:
        front_matter.append(f"description: {json.dumps(description)}")
    parts = ["---", *front_matter, "---", ""]
    if docstring:
        # Docstrings use double backticks for code; Markdown wants single ones
        parts += [escape_mdx_syntax(docstring.replace("``", "`")), ""]
    parts += ["```python", code, "```", ""]
    return "\n".join(parts)


def render_examples_index(readme: Path) -> str:
    """The README as the category's index page, its table linking the pages."""
    body = readme.read_text()
    body = re.sub(r"^# .*\n+", "", body, count=1)  # the front matter carries the title
    body = re.sub(r"\|\s*`(\w+)\.py`\s*\|", r"| [`\1.py`](./\1.md) |", body)
    return f"---\ntitle: Examples\n---\n\n{body.rstrip()}\n"


def generate_examples(target: ExamplesTarget) -> tuple[list[Path], list[str]]:
    """Render every example script of one target. Returns (written files, failures)."""
    written: list[Path] = []
    failures: list[str] = []

    print(f"\n[{target.label}]")
    print(f"  input:  {target.source_dir}")
    print(f"  output: {target.output_dir}")
    print("-" * 60)

    readme = target.source_dir / "README.md"
    order, descriptions = read_examples_index(readme)
    scripts = sorted(
        target.source_dir.glob("*.py"),
        key=lambda path: (
            order.index(path.stem) if path.stem in order else len(order),
            path.stem,
        ),
    )

    # The folder is generated as a whole: pages of renamed scripts must not linger
    target.output_dir.mkdir(parents=True, exist_ok=True)
    for stale in target.output_dir.glob("*.md"):
        stale.unlink()

    if readme.exists():
        index_file = target.output_dir / "index.md"
        index_file.write_text(render_examples_index(readme))
        written.append(index_file)
        print("  ✓ index.md")

    for position, script in enumerate(scripts, start=1):
        try:
            output = render_example_markdown(
                script, position, descriptions.get(script.stem, "")
            )
        except Exception as error:  # noqa: BLE001 — keep rendering the rest
            failures.append(f"{script.name}: {error}")
            print(f"  ✗ {script.name}: {error}")
            continue
        output_file = target.output_dir / f"{script.stem}.md"
        output_file.write_text(output)
        written.append(output_file)
        print(f"  ✓ {script.stem}.md")

    return written, failures


def generate_target(target: DocsTarget) -> tuple[list[Path], list[str]]:
    """Render every page of one target. Returns (written files, failures)."""
    written: list[Path] = []
    failures: list[str] = []

    print(f"\n[{target.label}]")
    print(f"  input:  {target.import_root}")
    print(f"  output: {target.output_dir}")
    print("-" * 60)

    for module_name, page_path in sorted(target.modules.items()):
        try:
            output = render_module_markdown(target.import_root, module_name)
        except Exception as error:  # noqa: BLE001 — keep rendering the rest
            failures.append(f"{module_name}: {error}")
            print(f"  ✗ {module_name}: {error}")
            continue

        if not output or not output.strip():
            failures.append(f"{module_name}: no documentable content")
            print(f"  ✗ {module_name}: no documentable content")
            continue

        output_file = target.output_dir / f"{page_path}.md"
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text(output)
        written.append(output_file)
        print(f"  ✓ {page_path}.md")

    return written, failures


def main() -> int:
    print("=" * 60)
    print("SDK Documentation Generator")
    print("=" * 60)

    all_written: list[Path] = []
    all_failures: list[str] = []
    for target in TARGETS:
        written, failures = generate_target(target)
        all_written.extend(written)
        all_failures.extend(failures)
    for examples in EXAMPLES:
        written, failures = generate_examples(examples)
        all_written.extend(written)
        all_failures.extend(failures)

    print()
    print("=" * 60)
    print(f"Generated {len(all_written)} documentation file(s)")
    if all_failures:
        print(f"Failed {len(all_failures)}:")
        for failure in all_failures:
            print(f"  - {failure}")
    print("=" * 60)
    return 1 if all_failures else 0


if __name__ == "__main__":
    sys.exit(main())
