import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 1. Documentation Tab (looks in docs/documentation)
  docsSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'documentation' 
    }
  ],

  // 2. Guides Tab (looks in docs/guides)
  guidesSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'guides' 
    }
  ],

  // 3. SDK/API Tab (looks in docs/sdk)
  sdkSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'sdk' 
    }
  ],
};

export default sidebars;