import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 1. Documentation Tab (looks in docs/documentation)
  docsSidebar: [
    {
      type: 'doc',
      id: 'documentation/quickstart',
      customProps: { icon: 'Sparkles' }
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsible: false,
      className: 'sidebar-section-header',
      items: [
        {
          type: 'doc',
          id: 'documentation/Core-Concepts/bucket',
          customProps: { icon: 'Archive' }
        },
        {
          type: 'doc',
          id: 'documentation/Core-Concepts/satellites',
          customProps: { icon: 'Satellite' }
        },
        {
          type: 'doc',
          id: 'documentation/Core-Concepts/luml_model',
          customProps: { icon: 'Box' }
        },
        {
          type: 'doc',
          id: 'documentation/Core-Concepts/organizations',
          customProps: { icon: 'Building2' }
        },
        {
          type: 'doc',
          id: 'documentation/Core-Concepts/orbit',
          customProps: { icon: 'Orbit' }
        },
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      collapsible: false,
      className: 'sidebar-section-header',
      items: [
        {
          type: 'doc',
          id: 'documentation/Modules/secrets',
          customProps: { icon: 'Lock' }
        },
        {
          type: 'doc',
          id: 'documentation/Modules/deployment',
          customProps: { icon: 'Rocket' }
        },
        {
          type: 'doc',
          id: 'documentation/Modules/data_agent',
          customProps: { icon: 'BotMessageSquare' }
        },
        {
          type: 'category',
          label: 'Registry',
          collapsible: true,
          customProps: { icon: 'Folders' },
          link: {
            type: 'doc',
            id: 'documentation/Modules/Registry/registry',
          },
          items: [
            {
              type: 'category',
              label: 'Model Registry',
              collapsible: true,
              link: {
                type: 'doc',
                id: 'documentation/Modules/Registry/Model-Registry/index',
              },
              items: [
                'documentation/Modules/Registry/Model-Registry/attachments',
                'documentation/Modules/Registry/Model-Registry/model_card',
                'documentation/Modules/Registry/Model-Registry/experiment_tracking',
              ],
            },
          ],
        },
        {
          type: 'doc',
          id: 'documentation/Modules/express_tasks',
          customProps: { icon: 'Zap' }
        },
        {
          type: 'doc',
          id: 'documentation/Modules/notebooks',
          customProps: { icon: 'Notebook' }
        },
      ],
    },
  ],

  // 2. Guides Tab (looks in docs/guides)
  guidesSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'guides' 
    }
  ],

  // 3. SDK/API Tab (looks in docs/sdk)
  sdkSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'sdk' 
    }
  ],
};

export default sidebars;